[package]
name = "dkdc"
version = "0.2.1"
edition = "2024"
description = "bookmarks for opening things from the terminal"
license = "MIT"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
