services:
  webapp:
    restart: always
    #image: lostmydockeraccount/dkdc:latest
    build: .
    container_name: webapp
    ports:
      - "8010:1913"
    networks:
      - dkdc-network
    command: ["dkdc", "gui", "--prod"]
    volumes:
      - $HOME/.dkdc:/root/.dkdc

networks:
  dkdc-network:
    driver: bridge
